/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantBatchesIndexRouteImport } from './routes/merchant/batches/index'
import { Route as MerchantBatchesBatchIdRouteImport } from './routes/merchant/batches/$batchId'
import { Route as MerchantBatchesNewRouteImport } from './routes/merchant/batches/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBatchesIndexRoute = MerchantBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBatchesBatchIdRoute = MerchantBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBatchesNewRoute = MerchantBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => MerchantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/batches/$batchId': typeof MerchantBatchesBatchIdRoute
  '/merchant/batches/new': typeof MerchantBatchesNewRoute
  '/merchant/batches/': typeof MerchantBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantIndexRoute
  '/merchant/batches/$batchId': typeof MerchantBatchesBatchIdRoute
  '/merchant/batches/new': typeof MerchantBatchesNewRoute
  '/merchant/batches': typeof MerchantBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/batches/$batchId': typeof MerchantBatchesBatchIdRoute
  '/merchant/batches/new': typeof MerchantBatchesNewRoute
  '/merchant/batches/': typeof MerchantBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/merchant'
    | '/merchant/'
    | '/merchant/batches/$batchId'
    | '/merchant/batches/new'
    | '/merchant/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/merchant'
    | '/merchant/batches/$batchId'
    | '/merchant/batches/new'
    | '/merchant/batches'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/merchant'
    | '/merchant/'
    | '/merchant/batches/$batchId'
    | '/merchant/batches/new'
    | '/merchant/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/batches/': {
      id: '/merchant/batches/'
      path: '/batches'
      fullPath: '/merchant/batches/'
      preLoaderRoute: typeof MerchantBatchesIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/batches/$batchId': {
      id: '/merchant/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/merchant/batches/$batchId'
      preLoaderRoute: typeof MerchantBatchesBatchIdRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/batches/new': {
      id: '/merchant/batches/new'
      path: '/batches/new'
      fullPath: '/merchant/batches/new'
      preLoaderRoute: typeof MerchantBatchesNewRouteImport
      parentRoute: typeof MerchantRoute
    }
  }
}

interface MerchantRouteChildren {
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantBatchesBatchIdRoute: typeof MerchantBatchesBatchIdRoute
  MerchantBatchesNewRoute: typeof MerchantBatchesNewRoute
  MerchantBatchesIndexRoute: typeof MerchantBatchesIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantBatchesBatchIdRoute: MerchantBatchesBatchIdRoute,
  MerchantBatchesNewRoute: MerchantBatchesNewRoute,
  MerchantBatchesIndexRoute: MerchantBatchesIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
