/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as AdminBatchesIndexRouteImport } from './routes/admin/batches/index'
import { Route as AdminBatchesBatchIdRouteImport } from './routes/admin/batches/$batchId'
import { Route as AdminRoutesIndexRouteImport } from './routes/admin/routes/index'
import { Route as MerchantBatchesIndexRouteImport } from './routes/merchant/batches/index'
import { Route as MerchantBatchesBatchIdRouteImport } from './routes/merchant/batches/$batchId'
import { Route as MerchantBatchesNewRouteImport } from './routes/merchant/batches/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminBatchesIndexRoute = AdminBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesBatchIdRoute = AdminBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesIndexRoute = AdminRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AdminRoute,
} as any)
const MerchantBatchesIndexRoute = MerchantBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBatchesBatchIdRoute = MerchantBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantBatchesNewRoute = MerchantBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => MerchantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/merchant/batches/$batchId': typeof MerchantBatchesBatchIdRoute
  '/merchant/batches/new': typeof MerchantBatchesNewRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/routes/': typeof AdminRoutesIndexRoute
  '/merchant/batches/': typeof MerchantBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/merchant/batches/$batchId': typeof MerchantBatchesBatchIdRoute
  '/merchant/batches/new': typeof MerchantBatchesNewRoute
  '/admin/batches': typeof AdminBatchesIndexRoute
  '/admin/routes': typeof AdminRoutesIndexRoute
  '/merchant/batches': typeof MerchantBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/merchant/batches/$batchId': typeof MerchantBatchesBatchIdRoute
  '/merchant/batches/new': typeof MerchantBatchesNewRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/routes/': typeof AdminRoutesIndexRoute
  '/merchant/batches/': typeof MerchantBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/merchant'
    | '/admin/login'
    | '/admin/'
    | '/merchant/'
    | '/admin/batches/$batchId'
    | '/merchant/batches/$batchId'
    | '/merchant/batches/new'
    | '/admin/batches/'
    | '/admin/routes/'
    | '/merchant/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/login'
    | '/admin'
    | '/merchant'
    | '/admin/batches/$batchId'
    | '/merchant/batches/$batchId'
    | '/merchant/batches/new'
    | '/admin/batches'
    | '/admin/routes'
    | '/merchant/batches'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/merchant'
    | '/admin_/login'
    | '/admin/'
    | '/merchant/'
    | '/admin/batches/$batchId'
    | '/merchant/batches/$batchId'
    | '/merchant/batches/new'
    | '/admin/batches/'
    | '/admin/routes/'
    | '/merchant/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/batches/': {
      id: '/admin/batches/'
      path: '/batches'
      fullPath: '/admin/batches/'
      preLoaderRoute: typeof AdminBatchesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches/$batchId': {
      id: '/admin/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/admin/batches/$batchId'
      preLoaderRoute: typeof AdminBatchesBatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes/': {
      id: '/admin/routes/'
      path: '/routes'
      fullPath: '/admin/routes/'
      preLoaderRoute: typeof AdminRoutesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/merchant/batches/': {
      id: '/merchant/batches/'
      path: '/batches'
      fullPath: '/merchant/batches/'
      preLoaderRoute: typeof MerchantBatchesIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/batches/$batchId': {
      id: '/merchant/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/merchant/batches/$batchId'
      preLoaderRoute: typeof MerchantBatchesBatchIdRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/batches/new': {
      id: '/merchant/batches/new'
      path: '/batches/new'
      fullPath: '/merchant/batches/new'
      preLoaderRoute: typeof MerchantBatchesNewRouteImport
      parentRoute: typeof MerchantRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBatchesBatchIdRoute: typeof AdminBatchesBatchIdRoute
  AdminBatchesIndexRoute: typeof AdminBatchesIndexRoute
  AdminRoutesIndexRoute: typeof AdminRoutesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBatchesBatchIdRoute: AdminBatchesBatchIdRoute,
  AdminBatchesIndexRoute: AdminBatchesIndexRoute,
  AdminRoutesIndexRoute: AdminRoutesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantBatchesBatchIdRoute: typeof MerchantBatchesBatchIdRoute
  MerchantBatchesNewRoute: typeof MerchantBatchesNewRoute
  MerchantBatchesIndexRoute: typeof MerchantBatchesIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantBatchesBatchIdRoute: MerchantBatchesBatchIdRoute,
  MerchantBatchesNewRoute: MerchantBatchesNewRoute,
  MerchantBatchesIndexRoute: MerchantBatchesIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
