/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppRoutesIndexRouteImport } from './routes/_app/routes/index'
import { Route as AppRoutesRouteIdIndexRouteImport } from './routes/_app/routes/$routeId/index'
import { Route as AppRoutesRouteIdStopsStopIdRouteImport } from './routes/_app/routes/$routeId/stops.$stopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesIndexRoute = AppRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRouteIdIndexRoute = AppRoutesRouteIdIndexRouteImport.update({
  id: '/routes/$routeId/',
  path: '/routes/$routeId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRouteIdStopsStopIdRoute =
  AppRoutesRouteIdStopsStopIdRouteImport.update({
    id: '/routes/$routeId/stops/$stopId',
    path: '/routes/$routeId/stops/$stopId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof AppMeRoute
  '/offers': typeof AppOffersRoute
  '/routes/': typeof AppRoutesIndexRoute
  '/routes/$routeId/': typeof AppRoutesRouteIdIndexRoute
  '/routes/$routeId/stops/$stopId': typeof AppRoutesRouteIdStopsStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof AppMeRoute
  '/offers': typeof AppOffersRoute
  '/routes': typeof AppRoutesIndexRoute
  '/routes/$routeId': typeof AppRoutesRouteIdIndexRoute
  '/routes/$routeId/stops/$stopId': typeof AppRoutesRouteIdStopsStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/me': typeof AppMeRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/routes/': typeof AppRoutesIndexRoute
  '/_app/routes/$routeId/': typeof AppRoutesRouteIdIndexRoute
  '/_app/routes/$routeId/stops/$stopId': typeof AppRoutesRouteIdStopsStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/offers'
    | '/routes/'
    | '/routes/$routeId/'
    | '/routes/$routeId/stops/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/offers'
    | '/routes'
    | '/routes/$routeId'
    | '/routes/$routeId/stops/$stopId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/me'
    | '/_app/offers'
    | '/_app/routes/'
    | '/_app/routes/$routeId/'
    | '/_app/routes/$routeId/stops/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/': {
      id: '/_app/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof AppRoutesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/$routeId/': {
      id: '/_app/routes/$routeId/'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId/'
      preLoaderRoute: typeof AppRoutesRouteIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/$routeId/stops/$stopId': {
      id: '/_app/routes/$routeId/stops/$stopId'
      path: '/routes/$routeId/stops/$stopId'
      fullPath: '/routes/$routeId/stops/$stopId'
      preLoaderRoute: typeof AppRoutesRouteIdStopsStopIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMeRoute: typeof AppMeRoute
  AppOffersRoute: typeof AppOffersRoute
  AppRoutesIndexRoute: typeof AppRoutesIndexRoute
  AppRoutesRouteIdIndexRoute: typeof AppRoutesRouteIdIndexRoute
  AppRoutesRouteIdStopsStopIdRoute: typeof AppRoutesRouteIdStopsStopIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMeRoute: AppMeRoute,
  AppOffersRoute: AppOffersRoute,
  AppRoutesIndexRoute: AppRoutesIndexRoute,
  AppRoutesRouteIdIndexRoute: AppRoutesRouteIdIndexRoute,
  AppRoutesRouteIdStopsStopIdRoute: AppRoutesRouteIdStopsStopIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
